### ISSUE TITLE
cli模板是否支持自定义？或者计划提供chorme插件？类似free-swagger的游览器插件

### ISSUE THREAD

**Issue by xubillde** [ztz2/api-helper#3]

**Comment by ztz2** [comment]
CLI生成的代码是简单特定的，这些都是固定场景使用，所以没有暴露自定义模版，但是有自定义事件回调，用于自定义函数名，TS代码的interface名称等等。如果需要自定义模版，可以使用本项目的web服务，提供了操作页面，模版编辑，接口字段选择等（内置了很多模版，接口，表单，类模版，mock数据模版等），web服务实现了swagger文档70%功能，一定程度上可以代替swagger文档，所以暂无计划提供chorme插件。

**Comment by xubillde** [comment]
嗯嗯好的
